### ISSUE TITLE
A connection to (http://myserver.ru/) was leaked.

### ISSUE THREAD

**Issue by LogosIntellect** [cdsap/Talaiot#61]
Hello, I have follow error.

`A connection to http://myserver.ru/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:115)
	at okhttp3.RealCall.execute(RealCall.java:87)
	at io.github.rybalkinsd.kohttp.dsl.HttpPostDslKt.httpPost(HttpPostDsl.kt:48)
	at io.github.rybalkinsd.kohttp.dsl.HttpPostDslKt.httpPost$default(HttpPostDsl.kt:46)
	at com.cdsap.talaiot.request.SimpleRequest.send(SimpleRequest.kt:20)
	at com.cdsap.talaiot.publisher.InfluxDbPublisher$publish$2.run(InfluxDbPublisher.kt:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by cdsap** [comment]
hi @LogosIntellect 
I saw the issue previously and that's why it was implemented before like:
https://github.com/cdsap/Talaiot/pull/53/files#diff-4ee317609fdaa9eaf26a6a6de480c8a0L38

@rybalkinsd suggested it was not the proper impl. We have more info how to apply it properly here:
https://github.com/square/okhttp/issues/2311

Next week we have a release and will be fixed.

**Comment by LogosIntellect** [comment]
@cdsap Thanks for the quick answer.

**Comment by rybalkinsd** [comment]
@cdsap You're right, thanks for the notice. Kohttp should have a DSL-level improvement for this issue

**Comment by cdsap** [comment]
Hi @LogosIntellect, 
I'm reopening the issue, I want to be sure that is correctly implemented following the comments of square/okhttp#2311 
Once is confirmed I will close again

**Comment by cdsap** [comment]
hi @LogosIntellect, can you reproduce this problem in the released version 0.3.0?

**Comment by LogosIntellect** [comment]
Hi @cdsap, this update fixes my problem
